"use client";
import { useAppDispatch, useAppSelector } from "@/store";
import { decrement, increment, initCounterState, resetCounter } from "@/store/counter/counterSlice";
import { useEffect } from "react";
// import { useState } from "react";
// Generated by https://quicktype.io

export interface CounterResponse {
  method: string;
  count: number;
}

const getApiCounter = async (): Promise<CounterResponse> => {
  const data = await fetch("/api/counter").then((res) => res.json());

  return data;
};

export default function CartCounter({ value = 0 }: { value: number }) {
  // const [counter, setCounter] = useState(value);
  const counter = useAppSelector((state) => state.counter.counter);
  const dispatch = useAppDispatch();

  useEffect(() => {
    getApiCounter().then(({ count }) => {
      dispatch(initCounterState(count));
    });
  }, []);

  // useEffect(() => {
  //   dispatch(initCounterState(value));
  // }, [dispatch, value]);

  return (
    <>
      <span className="text-9xl">{counter}</span>
      <div className="flex">
        <button
          onClick={() => dispatch(increment())}
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
        >
          +1
        </button>
        <button
          onClick={() => dispatch(decrement())}
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
        >
          -1
        </button>
      </div>
    </>
  );
}
